services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm start"

  test:
    build: .
    command: sh -c "npm install && npm run test"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
    depends_on:
      - app
